before_commands:
  - "composer install --prefer-source"

tools:
  php_code_coverage:
    enabled: true
    test_command: phpunit --configuration travis-phpunit.xml.dist
    filter:
      paths: ["src/*"]
      excluded_paths: ["tests/*", "vendor/*"]
  php_cpd: true
  php_loc:
    enabled: true
    command: phploc
    names:
      - '*.php'
  php_mess_detector: true
  php_pdepend: true
  php_analyzer:
    enabled: true
    filter:
      paths: ["src/", "tests/"]
  sensiolabs_security_checker: true
  external_code_coverage: true
